# You really need to use mamba or this env will need a year to be created
# Also : some dependencies explicit versions are kept, mostly these are obtained
# by trimming down the deepslice envs examples:
# https://github.com/PolarBean/DeepSlice/tree/master/conda_environments
# and fixing issues as mentioned in the explicit versions below
# it seems to work with for win64 machine
name: abba-brainglobe-deepslice
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl
  - numpy
  - pandas
  - pip
  - protobuf
  - scikit-image
  - scikit-learn
  - scipy
  - tensorflow=1.14.0 # modif 1: other wise the predictions from DeepSlice are bad with nan values everywhere
  - tqdm
  - jupyter
  - pyimagej
  - python
  - xarray
  - h5py=2.10.0 # modif 2: seems required for deepslice, otherwise a keras decode utf8 error is raiser
  - bg-atlasapi
  - openssl=1.1.1q # modif 3: dll not loaded error with netcdf4 on windows
  - openjdk=8 # 8 or 11 should work, pyimagej not tested for version above
  - netcdf4
  - pip:
    # works for regular pip packages
    - ipywidgets
    - ipyfilechooser
  
