name: abba-brainglobe-deepslice
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl
  - numpy
  - pandas
  - pip
  - protobuf
  - scikit-image
  - scikit-learn
  - scipy
  - tensorflow
  - tqdm
  - jupyter
  - pyimagej
  - python
  - h5py < 3.0.0
  - simpleitk
  - pip:
    - bg-atlasapi